return {
  -- "echasnovski/mini.statusline",
  -- event = "VeryLazy",
  -- opts = function()
  --   return {
  --     content = {
  --       active = function()
  --         local statusline = require "mini.statusline"
  --
  --         local fnamemodify = vim.fn.fnamemodify
  --
  --         local project_name = function()
  --           local current_project_folder = fnamemodify(vim.fn.getcwd(), ":t")
  --           local parent_project_folder = fnamemodify(vim.fn.getcwd(), ":h:t")
  --           return parent_project_folder .. "/" .. current_project_folder
  --         end
  --
  --         local lazy_plug_count = function()
  --           local stats = require("lazy").stats()
  --           return " " .. stats.count
  --         end
  --
  --         local lazy_startup = function()
  --           local stats = require("lazy").stats()
  --           local ms = (math.floor(stats.startuptime * 100 + 0.5) / 100)
  --           return " " .. ms .. "ms"
  --         end
  --
  --         local lazy_updates = function()
  --           return require("lazy.status").updates()
  --         end
  --
  --         -- local wtf = function()
  --         --   return require("wtf").get_status()
  --         -- end
  --
  --         local auto_format_indicator = function()
  --           if vim.g.vin_autoformat_enabled then
  --             return "󰉶 On"
  --           else
  --             return "󰉶 Off"
  --           end
  --         end
  --
  --         local mode, mode_hl = statusline.section_mode { trunc_width = 120 }
  --
  --         local spell = vim.wo.spell and (statusline.is_truncated(120) and "S" or "SPELL") or ""
  --         local wrap = vim.wo.wrap and (statusline.is_truncated(120) and "W" or "WRAP") or ""
  --         local git = statusline.section_git { trunc_width = 75 }
  --         local diagnostics = statusline.section_diagnostics { trunc_width = 75 }
  --         local searchcount = statusline.section_searchcount { trunc_width = 75 }
  --         local location = statusline.section_location { trunc_width = 120 }
  --         local fileinfo = statusline.section_fileinfo { trunc_width = 200 }
  --         local colorscheme = statusline.is_truncated(200) and "" or " " .. vim.g.colors_name
  --
  --         return statusline.combine_groups {
  --           { hl = mode_hl, strings = { mode } },
  --           {
  --             hl = "Function",
  --             strings = (statusline.is_truncated(250) and { git } or { project_name(), git }),
  --           },
  --
  --           "%<", -- Mark general truncate point
  --
  --           { hl = "Comment", strings = { location, diagnostics } },
  --
  --           "%=", -- End left alignment
  --
  --           { hl = "Comment", strings = { searchcount } },
  --           {
  --             hl = "Comment",
  --             strings = (
  --               statusline.is_truncated(120) and {}
  --               or {
  --                 -- wtf(),
  --                 wrap,
  --                 spell,
  --                 auto_format_indicator(),
  --                 lazy_plug_count(),
  --                 lazy_updates(),
  --                 lazy_startup(),
  --                 colorscheme,
  --               }
  --             ),
  --           },
  --           { hl = mode_hl, strings = { fileinfo } },
  --         }
  --       end,
  --     },
  --   }
  -- end,
  -- config = function(_, opts)
  --   require("mini.statusline").setup(opts)
  --   vim.opt.laststatus = 3
  -- end,
}
