-- Name:         rxyhn
-- Description:  Generated from palette
-- Last Updated: Thu 19 Mar 2026 12:21 p.m.

vim.cmd.hi('clear')
vim.g.colors_name = 'rxyhn'

-- stylua: ignore start
local baby_pink = { '#eb7f84' }
local black = { '#061115' }
local black2 = { '#0d181c' }
local blue = { '#6791C9' }
local cyan = { '#67AFC1' }
local dark_purple = { '#BC83E3' }
local darker_black = { '#000a0e' }
local folder_bg = { '#6791C9' }
local green = { '#78B892' }
local grey = { '#313c40' }
local grey_fg = { '#3b464a' }
local grey_fg2 = { '#455054' }
local lavender = { '#caa0e5' }
local light_grey = { '#4f5a5e' }
local line = { '#222d31' }
local maroon = { '#d97882' }
local nord_blue = { '#4f6b8b' }
local one_bg = { '#131e22' }
local one_bg2 = { '#1c272b' }
local one_bg3 = { '#242f33' }
local orange = { '#E89982' }
local pink = { '#F16269' }
local purple = { '#C488EC' }
local red = { '#DF5B61' }
local rosewater = { '#e98b8f' }
local sapphire = { '#70add5' }
local statusline = { '#0A1519' }
local sun = { '#e6d4a2' }
local teal = { '#7ACFE4' }
local vibrant_green = { '#8CD7AA' }
local white = { '#D9D7D6' }
local yellow = { '#ecd28b' }
-- stylua: ignore end

-- Terminal colors
-- stylua: ignore start
vim.g.terminal_color_0  = black2[1]
vim.g.terminal_color_1  = red[1]
vim.g.terminal_color_2  = green[1]
vim.g.terminal_color_3  = yellow[1]
vim.g.terminal_color_4  = blue[1]
vim.g.terminal_color_5  = purple[1]
vim.g.terminal_color_6  = cyan[1]
vim.g.terminal_color_7  = white[1]
vim.g.terminal_color_8  = grey[1]
vim.g.terminal_color_9  = red[1]
vim.g.terminal_color_10 = green[1]
vim.g.terminal_color_11 = yellow[1]
vim.g.terminal_color_12 = blue[1]
vim.g.terminal_color_13 = purple[1]
vim.g.terminal_color_14 = cyan[1]
vim.g.terminal_color_15 = white[1]
-- stylua: ignore end

-- Highlight groups
local hlgroups = {
  ColorColumn = { bg = one_bg2 },
  Conceal = { bold = true, fg = grey },
  CurSearch = { link = 'IncSearch' },
  Cursor = { bg = white, fg = black },
  CursorColumn = { link = 'CursorLine' },
  CursorIM = { link = 'Cursor' },
  CursorLine = { bg = black2 },
  CursorLineNr = { fg = white, bold = true },
  DebugPC = { bg = one_bg2 },
  DiffAdd = { fg = green },
  DiffAdded = { fg = green },
  DiffChange = { fg = sun },
  DiffChanged = { fg = yellow },
  DiffDelete = { fg = red },
  DiffDeleted = { fg = red },
  DiffNewFile = { fg = green },
  DiffOldFile = { fg = red },
  DiffRemoved = { fg = red },
  DiffText = { bg = one_bg3 },
  FloatBorder = { bg = darker_black, fg = line },
  FloatFooter = { bg = darker_black, fg = grey_fg },
  FloatTitle = { fg = white },
  FoldColumn = { fg = grey_fg },
  Folded = { bg = one_bg, fg = grey_fg2 },
  Ignore = { link = 'NonText' },
  IncSearch = { bg = orange, fg = black },
  LineNr = { fg = grey_fg },
  MatchParen = { bg = one_bg3 },
  ModeMsg = { fg = red, bold = true },
  MoreMsg = { fg = blue },
  MsgArea = { fg = white },
  MsgSeparator = { bg = black },
  NonText = { fg = one_bg3 },
  Normal = { bg = black, fg = white },
  NormalFloat = { bg = darker_black, fg = white },
  NormalNC = { link = 'Normal' },
  PmenuExtra = { fg = grey_fg },
  PmenuSbar = { bg = black2 },
  PmenuSel = { bg = black2, fg = 'NONE', bold = true },
  PmenuThumb = { bg = grey },
  Question = { link = 'MoreMsg' },
  QuickFixLine = { bg = one_bg },
  SignColumn = { fg = grey },
  SpellBad = { underdashed = true, sp = red },
  SpellCap = { underdashed = true, sp = yellow },
  SpellLocal = { underdashed = true, sp = blue },
  SpellRare = { underdashed = true, sp = purple },
  Substitute = { bg = red, fg = black },
  TabLine = { link = 'StatusLineNC' },
  TabLineFill = { link = 'Normal' },
  TabLineSel = { link = 'StatusLine' },
  TermCursor = { fg = black, bg = red },
  Title = { bold = true, fg = blue },
  Underlined = { fg = teal, underline = true },
  VertSplit = { link = 'WinSeparator' },
  Visual = { bg = one_bg3 },
  VisualNOS = { link = 'Visual' },
  Whitespace = { fg = one_bg3 },
  WildMenu = { link = 'Pmenu' },
  WinBar = { bg = black, fg = white },
  WinBarNC = { bg = black, fg = grey_fg },
  WinSeparator = { fg = line },
  lCursor = { link = 'Cursor' },
  HighlightedYankRegion = { reverse = true },
  Boolean = { fg = sun, italic = true, bold = true },
  Character = { link = 'String' },
  Comment = { fg = grey_fg, italic = true },
  Constant = { fg = orange, italic = true },
  Delimiter = { fg = orange },
  Error = { fg = red },
  Float = { link = 'Number' },
  Function = { fg = blue },
  Number = { fg = orange },
  SpecialKey = { fg = grey },
  String = { fg = green },
  Todo = { fg = black, bg = blue, bold = true },
  Type = { fg = yellow },
  PreProc = { fg = sapphire },
  PreCondit = { fg = purple },
  Include = { fg = dark_purple },
  Define = { fg = purple },
  Conditional = { fg = maroon },
  Repeat = { fg = teal },
  Typedef = { fg = teal },
  Exception = { fg = maroon },
  Statement = { fg = lavender },
  Keyword = { fg = pink, italic = true },
  Enum = { link = 'Macro' },
  Method = { link = 'Function' },
  Special = { fg = sun },
  SpecialChar = { fg = orange },
  WarningMsg = { link = 'DiagnosticWarn' },
  ErrorMsg = { fg = red },
  EndOfBuffer = { fg = black },
  Search = { fg = black, bg = teal },
  Identifier = { fg = lavender },
  Operator = { fg = rosewater, bold = true },
  Pmenu = { link = 'NormalFloat' },
  Macro = { fg = lavender },
  Directory = { fg = folder_bg },
  TSAnnotation = { fg = purple },
  TSAttribute = { fg = purple },
  TSBoolean = { fg = sun },
  TSComment = { fg = grey_fg },
  TSConditional = { fg = maroon },
  TSConstBuiltin = { fg = dark_purple },
  TSConstant = { fg = white },
  TSConstructor = { fg = green },
  TSField = { fg = blue },
  TSFloat = { fg = purple },
  TSFuncBuiltin = { fg = orange },
  TSFuncMacro = { fg = green },
  TSFunction = { fg = blue },
  TSFunctionCall = { fg = teal },
  TSInclude = { fg = blue },
  TSKeyword = { fg = pink },
  TSKeywordFunction = { fg = purple },
  TSKeywordOperator = { fg = maroon },
  TSKeywordReturn = { fg = teal },
  TSLabel = { fg = blue },
  TSMethod = { fg = blue },
  TSMethodCall = { fg = orange },
  TSNone = { fg = white },
  TSNumber = { fg = orange },
  TSOperator = { fg = pink },
  TSParameter = { fg = baby_pink },
  TSParameterReference = { fg = white },
  TSProperty = { fg = lavender },
  TSPunctBracket = { fg = lavender },
  TSStorageClass = { fg = blue },
  TSString = { fg = green },
  TSStringEscape = { fg = green },
  TSStringRegex = { fg = green },
  TSSymbol = { fg = nord_blue },
  TSTag = { fg = sun },
  TSTagAttribute = { fg = green },
  TSText = { fg = green },
  TSURI = { fg = vibrant_green },
  TSVariable = { fg = white },
  TSType = { fg = yellow, bold = true },
  TSTypeBuiltin = { fg = maroon },
  TSTypeDefinition = { fg = pink, bold = true },
  TSTypeQualifier = { fg = sun, bold = true },
  TSNamespace = { fg = blue },
  TSVariableBuiltin = { fg = pink, italic = true },
  TSPreProc = { link = 'PreProc' },
  TSDebug = { link = 'Debug' },
  TSDefine = { link = 'Define' },
  TSEnvironment = { link = 'Macro' },
  TSEnvironmentName = { link = 'Type' },
  TSError = { link = 'Error' },
  TSException = { fg = maroon },
  TSLiteral = { link = 'String' },
  TSMath = { fg = blue },
  TSRepeat = { fg = teal },
  TSStorageClassLifetime = { fg = blue },
  TSStrike = { fg = grey_fg },
  TSTitle = { link = 'Title' },
  TSTodo = { link = 'Todo' },
  TSTagDelimiter = { fg = green },
  ['@string'] = { fg = green },
  ['@keyword'] = { fg = pink },
  ['@function'] = { fg = purple },
  ['@type'] = { fg = yellow },
  ['@number'] = { fg = orange },
  ['@operator'] = { fg = pink },
  ['@variable'] = { fg = white },
  ['@text'] = { fg = green },
  ['@annotation'] = { fg = purple },
  ['@attribute'] = { fg = purple },
  ['@constant'] = { fg = orange },
  ['@constructor'] = { fg = rosewater },
  ['@field'] = { fg = blue },
  ['@include'] = { fg = dark_purple },
  ['@method'] = { fg = purple },
  ['@namespace'] = { fg = blue },
  ['@parameter'] = { fg = teal },
  ['@property'] = { fg = lavender },
  ['@statement'] = { fg = lavender },
  ['@comment'] = { fg = grey_fg },
  ['@boolean'] = { fg = sun },
  ['@conditional'] = { fg = red },
  ['@repeat'] = { fg = red },
  ['@label'] = { fg = blue },
  ['@float'] = { fg = purple },
  ['@function.builtin'] = { fg = orange },
  ['@function.call'] = { fg = purple },
  ['@method.call'] = { fg = orange },
  ['@keyword.function'] = { fg = purple },
  ['@type.builtin'] = { fg = maroon },
  ['@variable.parameter'] = { fg = teal },
  ['@variable.member'] = { fg = nord_blue },
  ['@variable.builtin'] = { fg = pink },
  ['@constant.builtin'] = { fg = dark_purple },
  ['@module'] = { fg = baby_pink },
  ['@function.method'] = { fg = teal },
  ['@markup.link'] = { fg = cyan },
  ['@markup.raw'] = { fg = lavender },
  ['@markup.heading'] = { fg = blue },
  ['@markup.list'] = { fg = sun },
  ['@markup.quote'] = { fg = black2 },
  ['@diff.plus'] = { fg = green },
  ['@diff.minus'] = { fg = red },
  ['@diff.delta'] = { fg = sun },
  ['@variable.member.key'] = { fg = nord_blue },
  ['@number.float'] = { fg = pink },
  ['@function.call.lua'] = { fg = nord_blue },
  ['@variable.member.lua'] = { fg = blue },
  ['@constructor.lua'] = { fg = rosewater },
  ['@function.lua'] = { fg = blue },
  ['@functional.call.lua'] = { fg = nord_blue },
  ['@lsp.type.variable.lua'] = { fg = white },
  ['@lsp.type.parameter.lua'] = { fg = sun },
  ['@lsp.type.function.lua'] = { fg = nord_blue },
  ['@lsp.type.property.lua'] = { fg = lavender },
  ['@lsp.type.method.lua'] = { fg = blue },
  ['@lsp.typemod.variable.global.lua'] = { fg = rosewater },
  ['@variable.parameter.lua'] = { fg = sun },
  ['@lsp.variable.lua'] = { fg = teal },
  ['@keyword.operator'] = { fg = maroon },
  ['@keyword.return'] = { fg = teal },
  ['@keyword.conditional'] = { fg = maroon },
  ['@keyword.repeat'] = { fg = teal },
  ['@keyword.exception'] = { fg = maroon },
  ['@keyword.import'] = { fg = dark_purple },
  ['@keyword.storage'] = { fg = yellow },
  ['@keyword.directive'] = { fg = yellow },
  ['@comment.todo'] = { fg = black, bg = white, bold = true },
  ['@comment.warning'] = { fg = black2, bg = yellow },
  ['@comment.danger'] = { fg = black2, bg = red },
  ['@markup.italic'] = { italic = true },
  ['@markup.strong'] = { bold = true },
  ['@markup.link.url'] = { fg = vibrant_green, italic = true, underline = true },
  ['@preproc'] = { link = 'TSPreProc' },
  ['@none'] = { link = 'TSNone' },
  ['@punctuation.bracket'] = { link = 'TSPunctBracket' },
  ['@punctuation.delimiter'] = { link = 'TSPunctDelimiter' },
  ['@punctuation.special'] = { link = 'TSPunctSpecial' },
  ['@storageclass'] = { link = 'TSStorageClass' },
  ['@storageclass.lifetime'] = { link = 'TSStorageClassLifetime' },
  ['@strike'] = { link = 'TSStrike' },
  ['@string.escape'] = { link = 'TSStringEscape' },
  ['@string.regex'] = { link = 'TSStringRegex' },
  ['@string.special'] = { link = 'TSStringSpecial' },
  ['@symbol'] = { link = 'TSSymbol' },
  ['@tag'] = { link = 'TSTag' },
  ['@tag.attribute'] = { link = 'TSTagAttribute' },
  ['@tag.delimiter'] = { link = 'TSTagDelimiter' },
  ['@text.danger'] = { link = 'TSDanger' },
  ['@text.diff.add'] = { link = 'DiffAdded' },
  ['@text.diff.delete'] = { link = 'DiffRemoved' },
  ['@text.environment'] = { link = 'TSEnvironment' },
  ['@text.environment.name'] = { link = 'TSEnvironmentName' },
  ['@text.literal'] = { link = 'TSLiteral' },
  ['@text.math'] = { link = 'TSMath' },
  ['@text.reference'] = { link = 'TSTextReference' },
  ['@text.strike'] = { link = 'TSStrike' },
  ['@text.title'] = { link = 'TSTitle' },
  ['@text.todo'] = { link = 'TSTodo' },
  ['@text.todo.checked'] = { link = 'Todo' },
  ['@text.todo.unchecked'] = { link = 'Ignore' },
  ['@text.underline'] = { link = 'TSUnderline' },
  ['@text.uri'] = { link = 'TSURI' },
  ['@text.warning'] = { link = 'TSWarning' },
  ['@todo'] = { link = 'TSTodo' },
  ['@type.definition'] = { link = 'TSTypeDefinition' },
  ['@type.qualifier'] = { link = 'TSTypeQualifier' },
  ['@uri'] = { link = 'TSURI' },
  TSDanger = { fg = red },
  DiagnosticError = { fg = red },
  DiagnosticHint = { fg = teal },
  DiagnosticInfo = { fg = cyan },
  DiagnosticOk = { fg = green },
  DiagnosticWarn = { fg = yellow },
  DiagnosticSignError = { fg = red },
  DiagnosticSignHint = { fg = teal },
  DiagnosticSignInfo = { fg = blue },
  DiagnosticSignWarn = { fg = yellow },
  DiagnosticUnderlineError = { sp = red, undercurl = true },
  DiagnosticUnderlineHint = { sp = teal, undercurl = true },
  DiagnosticUnderlineInfo = { sp = blue, undercurl = true },
  DiagnosticUnderlineWarn = { sp = yellow, undercurl = true },
  DiagnosticVirtualTextError = { bg = black2, fg = red },
  DiagnosticVirtualTextHint = { bg = black2, fg = teal },
  DiagnosticVirtualTextInfo = { bg = black2, fg = blue },
  DiagnosticVirtualTextWarn = { bg = black2, fg = yellow },
  DiagnosticUnnecessary = { fg = grey, sp = teal, undercurl = true },
  LspCodeLens = { fg = grey },
  LspReferenceText = { bg = one_bg3 },
  LspSignatureActiveParameter = { fg = sun },
  ['@lsp.mod.readonly'] = { link = 'Constant' },
  ['@lsp.mod.typeHint'] = { link = 'Type' },
  ['@lsp.type.builtinConstant'] = { link = '@constant.builtin' },
  ['@lsp.type.comment'] = { fg = 'NONE' },
  ['@lsp.type.macro'] = { fg = pink },
  ['@lsp.type.magicFunction'] = { link = '@function.builtin' },
  ['@lsp.type.method'] = { link = '@function.method' },
  ['@lsp.type.namespace'] = { link = '@module' },
  ['@lsp.type.parameter'] = { link = '@variable.parameter' },
  ['@lsp.type.selfParameter'] = { link = '@variable.builtin' },
  ['@lsp.type.variable'] = { fg = 'NONE' },
  ['@lsp.typemod.function.builtin'] = { link = '@function.builtin' },
  ['@lsp.typemod.function.defaultLibrary'] = { link = '@function.builtin' },
  ['@lsp.typemod.function.readonly'] = { bold = true, fg = blue },
  ['@lsp.typemod.keyword.documentation'] = { link = 'Special' },
  ['@lsp.typemod.method.defaultLibrary'] = { link = '@function.builtin' },
  ['@lsp.typemod.operator.controlFlow'] = { link = '@keyword.exception' },
  ['@lsp.typemod.operator.injected'] = { link = 'Operator' },
  ['@lsp.typemod.string.injected'] = { link = 'String' },
  ['@lsp.typemod.variable.defaultLibrary'] = { link = '@variable.builtin' },
  ['@lsp.typemod.variable.injected'] = { link = '@variable' },
  ['@lsp.typemod.variable.static'] = { link = 'Constant' },
  ['@lsp.property.go'] = { link = 'Function' },
  ['@lsp.type.go'] = { link = 'Keyword' },
  ['@lsp.type.keyword.go'] = { link = 'Keyword' },
  ['@lsp.type.builtin.go'] = { fg = pink },
  ['@lsp.variable.member.go'] = { fg = blue },
  ['@type.go'] = { fg = purple, bold = true },
  ['@keyword.function.go'] = { fg = purple, italic = true },
  ['@variable.member.go'] = { fg = nord_blue },
  ['@variable.parameter.go'] = { fg = teal },
  ['@function.method.go'] = { fg = teal },
  ['@lsp.type.interface.go'] = { fg = yellow, italic = true },
  ['@lsp.type.struct.go'] = { fg = purple },
  ['@lsp.type.variable.go'] = { fg = white },
  ['@lsp.type.parameter.go'] = { fg = pink },
  ['@lsp.type.function.go'] = { fg = blue },
  ['@lsp.type.method.go'] = { fg = blue },
  ['@lsp.type.namespace.go'] = { fg = orange },
  ['@lsp.mod.readonly.go'] = { fg = orange, bold = true },
  ['@lsp.mod.format.go'] = { fg = rosewater },
  ['@function.builtin.go'] = { fg = orange, bold = true },
  LspInfoBorder = { link = 'FloatBorder' },
  LspReferenceRead = { link = 'LspReferenceText' },
  LspReferenceWrite = { bg = one_bg3 },
  gitHash = { fg = grey },
  bashSpecialVariables = { link = 'Constant' },
  shAstQuote = { link = 'Constant' },
  shCaseEsac = { link = 'Operator' },
  shDeref = { link = 'Special' },
  shDerefSimple = { link = 'shDerefVar' },
  shDerefVar = { link = 'Constant' },
  shNoQuote = { link = 'shAstQuote' },
  shQuote = { link = 'String' },
  shTestOpr = { link = 'Operator' },
  htmlBold = { bold = true },
  htmlBoldItalic = { bold = true, italic = true },
  htmlH1 = { fg = red, bold = true },
  htmlH2 = { fg = red, bold = true },
  htmlH3 = { fg = red, bold = true },
  htmlH4 = { fg = red, bold = true },
  htmlH5 = { fg = red, bold = true },
  htmlH6 = { fg = red, bold = true },
  htmlItalic = { italic = true },
  htmlLink = { fg = blue, underline = true },
  htmlSpecialChar = { link = 'SpecialChar' },
  htmlSpecialTagName = { fg = purple },
  htmlString = { link = 'String' },
  htmlTagName = { link = 'Tag' },
  htmlTitle = { link = 'Title' },
  markdownBold = { bold = true },
  markdownCode = { fg = green },
  markdownListMarker = { fg = sun },
  healthError = { fg = red },
  healthSuccess = { fg = green },
  healthWarning = { fg = yellow },
  markdownBoldItalic = { bold = true, italic = true },
  markdownCodeBlock = { fg = green },
  markdownError = { fg = 'NONE' },
  markdownEscape = { fg = 'NONE' },
  markdownH1 = { link = 'htmlH1' },
  markdownH2 = { link = 'htmlH2' },
  markdownH3 = { link = 'htmlH3' },
  markdownH4 = { link = 'htmlH4' },
  markdownH5 = { link = 'htmlH5' },
  markdownH6 = { link = 'htmlH6' },
  helpHeader = { link = 'Title' },
  helpSectionDelim = { link = 'Title' },
  qfFileName = { link = 'Directory' },
  qfLineNr = { link = 'LineNr' },
  GitSignsAdd = { link = 'DiffAdd' },
  GitSignsChange = { link = 'DiffChange' },
  GitSignsDelete = { link = 'DiffDelete' },
  -- Telescope
  TelescopeBorder = { bg = black2, fg = line },
  TelescopeNormal = { bg = black2, fg = white },
  TelescopeMatching = { fg = red, bold = true },
  TelescopeSelection = { link = 'Visual' },
  TelescopeTitle = { bg = teal, fg = black },
  TelescopeResultsTitle = { fg = black, bg = black },
  TelescopePromptBorder = { bg = one_bg, fg = line },
  TelescopePromptNormal = { bg = one_bg, fg = white },
  TelescopeResultsClass = { link = 'Structure' },
  TelescopeResultsField = { link = '@variable.member' },
  TelescopeResultsMethod = { link = 'Function' },
  TelescopeResultsStruct = { link = 'Structure' },
  TelescopeResultsVariable = { link = '@variable' },
  -- Snacks
  SnacksPickerBorder = { fg = darker_black, bg = darker_black },
  SnacksPickerTitle = { fg = darker_black, bg = red },
  SnacksPickerListCursorLine = { bg = black2, bold = true },
  SnacksPickerBufType = { bg = red },
  SnacksPickerPreviewBorder = { fg = darker_black, bg = darker_black },
  SnacksPickerPreview = { bg = darker_black },
  SnacksPickerPreviewTitle = { fg = darker_black, bg = green },
  SnacksPickerBoxBorder = { fg = darker_black, bg = darker_black },
  SnacksPickerBox = { fg = white, bg = darker_black },
  SnacksPickerInputBorder = { fg = darker_black, bg = darker_black },
  SnacksPickerInputSearch = { fg = red, bg = darker_black },
  SnacksPickerInput = { bg = darker_black },
  SnacksPickerList = { bg = darker_black },
  SnacksPickerListTitle = { fg = darker_black, bg = darker_black },
  SnacksPickerCursorLine = { bg = darker_black },
  SnacksTitle = { fg = one_bg, bg = red },
  SnacksPickerDir = { fg = grey_fg2 },
  SnacksPickerPathHidden = { fg = grey_fg },
  SnacksPickerMatch = { link = 'IncSearch' },
  SnacksPicker = { bg = one_bg },
  -- DapUI
  DapUIBreakpointsCurrentLine = { bold = true, fg = white },
  DapUIBreakpointsDisabledLine = { link = 'Comment' },
  DapUIBreakpointsInfo = { fg = blue },
  DapUIBreakpointsPath = { link = 'Directory' },
  DapUIDecoration = { fg = line },
  DapUIFloatBorder = { fg = line },
  DapUILineNumber = { fg = teal },
  DapUIModifiedValue = { bold = true, fg = teal },
  DapUIPlayPause = { fg = green },
  DapUIRestart = { fg = green },
  DapUIScope = { link = 'Special' },
  DapUISource = { fg = red },
  DapUIStepBack = { fg = teal },
  DapUIStepInto = { fg = teal },
  DapUIStepOut = { fg = teal },
  DapUIStepOver = { fg = teal },
  DapUIStop = { fg = red },
  DapUIStoppedThread = { fg = teal },
  DapUIThread = { fg = white },
  DapUIType = { link = 'Type' },
  DapUIUnavailable = { fg = grey },
  DapUIWatchesEmpty = { fg = red },
  DapUIWatchesError = { fg = red },
  DapUIWatchesValue = { fg = white },
  -- WhichKey
  WhichKeyDesc = { fg = pink },
  WhichKeyGroup = { fg = blue },
  WhichKeyFloat = { bg = black2 },
  -- Flash.nvim
  FlashLabel = { fg = green },
  FlashMatch = { fg = purple },
  FlashCurrent = { fg = sun },
  FlashPrompt = { link = 'NormalFloat' },
  FlashBackdrop = { fg = light_grey },
  -- Trouble
  TroublePreview = { fg = red, bg = one_bg, bold = true },
  -- lazy.nvim
  LazyProgressTodo = { fg = grey },
  -- misc
  InfoMsg = { link = 'DiagnosticInfo' },
  HintMsg = { link = 'DiagnosticHint' },
  SpecialWindowBG = { bg = darker_black },
  FocusedWindow = { fg = white, bg = black },
  UnfocusedWindow = { fg = grey },
  ColorfulWinSep = { fg = red },
  HighlightURL = { fg = teal, underline = true },
  -- Fugitive
  fugitiveHash = { link = 'gitHash' },
  fugitiveHeader = { link = 'Title' },
  fugitiveHeading = { link = 'Title' },
  fugitiveStagedHeading = { fg = green, bold = true },
  fugitiveStagedModifier = { fg = green },
  fugitiveUnStagedHeading = { fg = yellow, bold = true },
  fugitiveUnstagedModifier = { fg = yellow },
  fugitiveUntrackedHeading = { fg = teal, bold = true },
  fugitiveUntrackedModifier = { fg = teal },
  StatusLine = { bg = statusline, fg = white },
  StatusLineNC = { bg = black2, fg = grey_fg },
  StatusLineSeparator = { fg = black2, bg = statusline },
  StatusLineGitAdded = { bg = statusline, fg = green },
  StatusLineGitChanged = { bg = statusline, fg = yellow },
  StatusLineGitRemoved = { bg = statusline, fg = red },
  StatusLineGitBranch = { bg = statusline, fg = grey_fg },
  StatusLineGitAdd = { fg = green, bg = statusline },
  StatusLineGitChange = { fg = one_bg3, bg = statusline },
  StatusLineGitDelete = { fg = red, bg = statusline },
  StatusLineLspError = { bg = statusline, fg = red },
  StatusLineLspWarn = { bg = statusline, fg = yellow },
  StatusLineLspINFO = { bg = statusline, fg = cyan },
  StatusLineLspHint = { bg = statusline, fg = teal },
  StatusLineFilename = { bg = statusline, fg = white },
  StatusLineHeader = { bg = one_bg3, fg = white },
  StatusLineDimmed = { bg = statusline, fg = grey_fg },
  StatusLineHeaderModified = { bg = green, fg = black },
  StatusLineHeaderError = { bg = red, fg = black },
  LspReady = { fg = green, bg = statusline },
  StatusLineFileError = { fg = red, bg = statusline },
  StatusLineFileModified = { fg = green, bg = statusline },
  StatusLineFileMacro = { fg = green, bg = statusline },
  LspSpinner = { fg = maroon, bg = statusline, bold = true },
}

-- Set highlight groups
for name, attr in pairs(hlgroups) do
  attr.ctermbg = attr.bg and attr.bg[2]
  attr.ctermfg = attr.fg and attr.fg[2]
  attr.bg = attr.bg and attr.bg[1]
  attr.fg = attr.fg and attr.fg[1]
  attr.sp = attr.sp and attr.sp[1]
  vim.api.nvim_set_hl(0, name, attr)
end
